#!/usr/bin/env bash
# generate-agents-yaml.sh — reads terraform output and writes a complete agents.yaml.
# Run after terraform apply for at least module.foundation and module.observability.
#
# Usage:
#   ./scripts/generate-agents-yaml.sh [environment]
#
# Example (writes directly to forge-mvp):
#   ./scripts/generate-agents-yaml.sh dev > ../forge-mvp/agents.yaml

set -euo pipefail

ENV="${1:-dev}"
# Optional org package root. Filters which files the scanner picks up;
# empty = migrate everything under source_dir. Never renames packages.
SCOPE_PACKAGE_PREFIX="${FORGE_SCOPE_PACKAGE_PREFIX:-}"

# Resolve the forge-terraform directory relative to this script's location
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TF_DIR="${SCRIPT_DIR}/.."

echo "==> Reading terraform outputs from: ${TF_DIR}" >&2
cd "$TF_DIR"

TF_OUTPUT="$(terraform output -json 2>/dev/null)"

if [[ -z "$TF_OUTPUT" ]] || [[ "$TF_OUTPUT" == "{}" ]]; then
  echo "ERROR: No terraform outputs found. Run terraform apply first." >&2
  exit 1
fi

# Extract values — use // empty to handle null/missing outputs gracefully
AWS_REGION="$(echo "$TF_OUTPUT" | jq -r '.aws_region.value // "us-east-1"')"
DYNAMODB_TABLE="$(echo "$TF_OUTPUT" | jq -r '.dynamodb_state_table.value // ""')"
CHECKPOINT_TABLE="$(echo "$TF_OUTPUT" | jq -r '.dynamodb_checkpoint_table.value // ""')"
GUARDRAIL_ID="$(echo "$TF_OUTPUT" | jq -r '.guardrail_id.value // ""')"
GUARDRAIL_VERSION="$(echo "$TF_OUTPUT" | jq -r '.guardrail_version.value // ""')"
LOG_GROUP="$(echo "$TF_OUTPUT" | jq -r '.cloudwatch_log_group.value // ""')"
SQS_URL="$(echo "$TF_OUTPUT" | jq -r '.sqs_queue_url.value // ""')"
KB_ID="$(echo "$TF_OUTPUT" | jq -r '.knowledge_base_id.value // ""')"
SM_ENDPOINT="$(echo "$TF_OUTPUT" | jq -r '.sagemaker_endpoint_name.value // ""')"

# Emit agents.yaml to stdout — caller redirects with >
cat <<EOF
# Generated by generate-agents-yaml.sh — do not edit manually.
# Re-generate after any terraform apply:
#   ./scripts/generate-agents-yaml.sh ${ENV} > ../forge-mvp/agents.yaml

# ─── Models ───────────────────────────────────────────────────────────────────
transform_model: "us.anthropic.claude-sonnet-4-5-20250929-v1:0"
review_model: "us.amazon.nova-pro-v1:0"

# ─── AWS ──────────────────────────────────────────────────────────────────────
aws_region: "${AWS_REGION}"

# ─── DynamoDB ─────────────────────────────────────────────────────────────────
dynamodb_table: "${DYNAMODB_TABLE}"
dynamodb_checkpoint_table: "${CHECKPOINT_TABLE}"

# ─── Bedrock Guardrails ───────────────────────────────────────────────────────
guardrail_id: "${GUARDRAIL_ID}"
guardrail_version: "${GUARDRAIL_VERSION}"

# ─── CloudWatch ───────────────────────────────────────────────────────────────
cloudwatch_namespace: "FORGE/Migration"
cloudwatch_log_group: "${LOG_GROUP}"

# ─── Optional: SQS (deploy module.sqs before Phase 6) ────────────────────────
sqs_queue_url: "${SQS_URL}"

# ─── Optional: RAG (deploy module.rag before Phase 6) ────────────────────────
knowledge_base_id: "${KB_ID}"

# ─── Optional: SageMaker internal LLM (future) ───────────────────────────────
sagemaker_endpoint_name: "${SM_ENDPOINT}"

# ─── Migration settings ───────────────────────────────────────────────────────
source_java_version: "8"
target_java_version: "21"
pass_threshold: 80
retry_threshold: 50
max_retries: 2
# Which files are ours to migrate. Filters at scan time by the file's declared
# package, so an out-of-scope file costs zero Bedrock calls. Empty (the default)
# migrates everything under source_dir. Matching is on a package boundary, so
# "com.corp" covers com.corp.user but not com.corporate. Files with no package
# declaration (XML configs, default-package classes) are always in scope.
# This NEVER renames a package — the declaration is read, never rewritten.
scope_package_prefix: "${SCOPE_PACKAGE_PREFIX}"
complexity_block_threshold: 2000

# ─── Cost model (drives estimated_cost_usd + the FORGE-CostSpike alarm) ──────
# USD per 1,000 tokens. Update when Bedrock pricing changes — no code change needed.
model_pricing:
  "us.anthropic.claude-sonnet-4-5-20250929-v1:0":
    input_per_1k: 0.003
    output_per_1k: 0.015
  "us.amazon.nova-pro-v1:0":
    input_per_1k: 0.0008
    output_per_1k: 0.0032

# Publish pipeline counters to the FORGE/Migration namespace. The Terraform
# alarms and dashboard read these; turning it off leaves them blind.
emit_cloudwatch_metrics: true

# ─── Build verification ───────────────────────────────────────────────────────
# A file can score 95 and still not compile. When enabled, each written file is
# compiled and a failure is fed back to the transform agent as review feedback.
#   mode: javac   — fast syntax/symbol check of the single file
#         maven   — mvn -q compile at the output project root (needs a pom.xml)
#         command — run `command` verbatim; {file} and {output_dir} are substituted
build_verification:
  enabled: false
  mode: "javac"
  command: ""
  classpath: ""
  timeout_seconds: 300

# ─── LangSmith observability ─────────────────────────────────────────────────
langsmith_project: "forge-migration"
EOF

echo "==> agents.yaml written to stdout. Redirect to your target file." >&2
