#!/usr/bin/env bash
# generate-agents-yaml.sh — reads terraform output and writes a complete agents.yaml.
# Run after terraform apply for at least module.foundation and module.observability.
#
# Usage:
#   ./scripts/generate-agents-yaml.sh [environment]
#
# Example (writes directly to forge-mvp):
#   ./scripts/generate-agents-yaml.sh dev > ../forge-mvp/agents.yaml

set -euo pipefail

ENV="${1:-dev}"

# Resolve the forge-terraform directory relative to this script's location
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TF_DIR="${SCRIPT_DIR}/.."

echo "==> Reading terraform outputs from: ${TF_DIR}" >&2
cd "$TF_DIR"

TF_OUTPUT="$(terraform output -json 2>/dev/null)"

if [[ -z "$TF_OUTPUT" ]] || [[ "$TF_OUTPUT" == "{}" ]]; then
  echo "ERROR: No terraform outputs found. Run terraform apply first." >&2
  exit 1
fi

# Extract values — use // empty to handle null/missing outputs gracefully
AWS_REGION="$(echo "$TF_OUTPUT" | jq -r '.aws_region.value // "us-east-1"')"
DYNAMODB_TABLE="$(echo "$TF_OUTPUT" | jq -r '.dynamodb_state_table.value // ""')"
CHECKPOINT_TABLE="$(echo "$TF_OUTPUT" | jq -r '.dynamodb_checkpoint_table.value // ""')"
GUARDRAIL_ID="$(echo "$TF_OUTPUT" | jq -r '.guardrail_id.value // ""')"
GUARDRAIL_VERSION="$(echo "$TF_OUTPUT" | jq -r '.guardrail_version.value // ""')"
LOG_GROUP="$(echo "$TF_OUTPUT" | jq -r '.cloudwatch_log_group.value // ""')"
SQS_URL="$(echo "$TF_OUTPUT" | jq -r '.sqs_queue_url.value // ""')"
KB_ID="$(echo "$TF_OUTPUT" | jq -r '.knowledge_base_id.value // ""')"
SM_ENDPOINT="$(echo "$TF_OUTPUT" | jq -r '.sagemaker_endpoint_name.value // ""')"

# Emit agents.yaml to stdout — caller redirects with >
cat <<EOF
# Generated by generate-agents-yaml.sh — do not edit manually.
# Re-generate after any terraform apply:
#   ./scripts/generate-agents-yaml.sh ${ENV} > ../forge-mvp/agents.yaml

# ─── Models ───────────────────────────────────────────────────────────────────
transform_model: "us.anthropic.claude-sonnet-4-5-20250929-v1:0"
review_model: "us.amazon.nova-pro-v1:0"

# ─── AWS ──────────────────────────────────────────────────────────────────────
aws_region: "${AWS_REGION}"

# ─── DynamoDB ─────────────────────────────────────────────────────────────────
dynamodb_table: "${DYNAMODB_TABLE}"
dynamodb_checkpoint_table: "${CHECKPOINT_TABLE}"

# ─── Bedrock Guardrails ───────────────────────────────────────────────────────
guardrail_id: "${GUARDRAIL_ID}"
guardrail_version: "${GUARDRAIL_VERSION}"

# ─── CloudWatch ───────────────────────────────────────────────────────────────
cloudwatch_namespace: "FORGE/Migration"
cloudwatch_log_group: "${LOG_GROUP}"

# ─── Optional: SQS (deploy module.sqs before Phase 6) ────────────────────────
sqs_queue_url: "${SQS_URL}"

# ─── Optional: RAG (deploy module.rag before Phase 6) ────────────────────────
knowledge_base_id: "${KB_ID}"

# ─── Optional: SageMaker internal LLM (future) ───────────────────────────────
sagemaker_endpoint_name: "${SM_ENDPOINT}"

# ─── Migration settings ───────────────────────────────────────────────────────
source_java_version: "8"
target_java_version: "21"
pass_threshold: 80
retry_threshold: 50
max_retries: 2
scope_package_prefix: "com.corp"
complexity_block_threshold: 2000
secret_scan_enabled: true         # Gate 0: deterministic local secret scan before any model call

# ─── RAG (prompt-stuffing; no OpenSearch) ───────────────────────────────────────
rag_mode: "prompt_stuff"          # off | prompt_stuff | knowledge_base
rag_docs_dir: ""                  # empty = default ../forge-terraform/docs
rag_max_chars: 6000

# ─── Cost / build ───────────────────────────────────────────────────────────────
avg_cost_per_bedrock_call: 0.02
build_tool: "none"                # maven | gradle | none (future compile gate)

# ─── LangSmith observability ─────────────────────────────────────────────────
langsmith_project: "forge-migration"
EOF

echo "==> agents.yaml written to stdout. Redirect to your target file." >&2
