#!/usr/bin/env bash
# generate-agents-yaml.sh — reads terraform output and writes a complete agents.yaml.
# Run after terraform apply for at least module.foundation and module.observability.
#
# Usage:
#   ./scripts/generate-agents-yaml.sh [environment]
#
# Example (writes directly to forge-mvp):
#   ./scripts/generate-agents-yaml.sh dev > ../forge-mvp/agents.yaml

set -euo pipefail

ENV="${1:-dev}"
# Optional org package root. Filters which files the scanner picks up;
# empty = migrate everything under source_dir. Never renames packages.
SCOPE_PACKAGE_PREFIX="${FORGE_SCOPE_PACKAGE_PREFIX:-}"

# Resolve the forge-terraform directory relative to this script's location
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TF_DIR="${SCRIPT_DIR}/.."

echo "==> Reading terraform outputs from: ${TF_DIR}" >&2
cd "$TF_DIR"

TF_OUTPUT="$(terraform output -json 2>/dev/null)"

if [[ -z "$TF_OUTPUT" ]] || [[ "$TF_OUTPUT" == "{}" ]]; then
  echo "ERROR: No terraform outputs found. Run terraform apply first." >&2
  exit 1
fi

# Extract values — use // empty to handle null/missing outputs gracefully
AWS_REGION="$(echo "$TF_OUTPUT" | jq -r '.aws_region.value // "us-east-1"')"
DYNAMODB_TABLE="$(echo "$TF_OUTPUT" | jq -r '.dynamodb_state_table.value // ""')"
CHECKPOINT_TABLE="$(echo "$TF_OUTPUT" | jq -r '.dynamodb_checkpoint_table.value // ""')"
GUARDRAIL_ID="$(echo "$TF_OUTPUT" | jq -r '.guardrail_id.value // ""')"
GUARDRAIL_VERSION="$(echo "$TF_OUTPUT" | jq -r '.guardrail_version.value // ""')"
LOG_GROUP="$(echo "$TF_OUTPUT" | jq -r '.cloudwatch_log_group.value // ""')"
SQS_URL="$(echo "$TF_OUTPUT" | jq -r '.sqs_queue_url.value // ""')"
SM_ENDPOINT="$(echo "$TF_OUTPUT" | jq -r '.sagemaker_endpoint_name.value // ""')"

# Emit agents.yaml to stdout — caller redirects with >
cat <<EOF
# Generated by generate-agents-yaml.sh — do not edit manually.
# Re-generate after any terraform apply:
#   ./scripts/generate-agents-yaml.sh ${ENV} > ../forge-mvp/agents.yaml

# ─── Models ───────────────────────────────────────────────────────────────────
transform_model: "us.anthropic.claude-opus-4-8"
review_model: "us.amazon.nova-pro-v1:0"

# ─── AWS ──────────────────────────────────────────────────────────────────────
aws_region: "${AWS_REGION}"

# ─── DynamoDB ─────────────────────────────────────────────────────────────────
dynamodb_table: "${DYNAMODB_TABLE}"
dynamodb_checkpoint_table: "${CHECKPOINT_TABLE}"

# ─── Bedrock Guardrails ───────────────────────────────────────────────────────
guardrail_id: "${GUARDRAIL_ID}"
guardrail_version: "${GUARDRAIL_VERSION}"

# ─── CloudWatch ───────────────────────────────────────────────────────────────
cloudwatch_namespace: "FORGE/Migration"
cloudwatch_log_group: "${LOG_GROUP}"

# ─── Optional: SQS (deploy module.sqs before Phase 6) ────────────────────────
sqs_queue_url: "${SQS_URL}"

# ─── Optional: SageMaker internal LLM (future) ───────────────────────────────
sagemaker_endpoint_name: "${SM_ENDPOINT}"

# ─── Migration settings ───────────────────────────────────────────────────────
source_java_version: "8"
target_java_version: "21"
pass_threshold: 80
retry_threshold: 50
max_retries: 2
# Which files are ours to migrate. Filters at scan time by the file's declared
# package, so an out-of-scope file costs zero Bedrock calls. Empty (the default)
# migrates everything under source_dir. Matching is on a package boundary, so
# "com.corp" covers com.corp.user but not com.corporate. Files with no package
# declaration (XML configs, default-package classes) are always in scope.
# This NEVER renames a package — the declaration is read, never rewritten.
scope_package_prefix: "${SCOPE_PACKAGE_PREFIX}"
complexity_block_threshold: 2000

# ─── The secret gate ──────────────────────────────────────────────────────────
# Local, deterministic, and ahead of EVERY remote call — ApplyGuardrail included.
# A file carrying a credential is refused while its bytes are still in the
# process, for zero Bedrock calls. Nothing downstream can substitute for this:
# the Bedrock guardrail is itself a network call and covers only six entity
# types, and a model asked "does this file contain secrets?" has already been
# shown the secret.
#   action: block -> BLOCKED. warn -> a finding only, and the file IS then sent.
#   entropy      -> catches base64-shaped credentials with no vendor prefix.
#   allow        -> regexes for literals the team has cleared (test vectors,
#                   sample tokens); a matching line is dropped from findings.
secret_scan:
  enabled: true
  action: block
  entropy:
    enabled: true
    min_length: 20
    min_bits: 4.0
  allow: []

# ─── Optional qualitative pre-flight ─────────────────────────────────────────
# OFF: sending source to a model to look for secrets is the disclosure a secret
# policy forbids, and every other question the check used to ask is now answered
# locally. Enable only for the migration-safety questions in guardrails_pre, and
# only if your policy permits source to reach a model before the gate clears it.
preflight_model_check: false

# ─── Cost model (drives estimated_cost_usd + the FORGE-CostSpike alarm) ──────
# USD per 1,000 tokens. Update when Bedrock pricing changes — no code change needed.
model_pricing:
  "us.anthropic.claude-opus-4-8":
    input_per_1k: 0.005
    output_per_1k: 0.025
  "us.amazon.nova-pro-v1:0":
    input_per_1k: 0.0008
    output_per_1k: 0.0032

# Publish pipeline counters to the FORGE/Migration namespace. The Terraform
# alarms and dashboard read these; turning it off leaves them blind.
emit_cloudwatch_metrics: true

# ─── Build verification ───────────────────────────────────────────────────────
# A file can score 95 and still not compile. When enabled, each written file is
# compiled and a failure is fed back to the transform agent as review feedback.
#   mode: javac   — fast syntax/symbol check of the single file
#         maven   — mvn -q compile at the output project root (needs a pom.xml)
#         command — run \`command\` verbatim; {file} and {output_dir} are substituted
build_verification:
  enabled: false
  mode: "javac"
  command: ""
  classpath: ""
  timeout_seconds: 300

# ─── Decisions ────────────────────────────────────────────────────────────────
# Project-level choices that packs read (see prompts/FORGE-Platform-Requirements.md
# §4). An acceptance check guarded by \`when:\` is skipped — never passed — while
# the decision it names is unset.
decisions:
  web_framework: modernize-in-place     # modernize-in-place | migrate-to-spring
  runtime: war-xml-bootstrap            # war-xml-bootstrap | war-programmatic-bootstrap
  container: liberty                    # liberty | wildfly | tomcat | jetty
  views: in-place                       # in-place | thymeleaf | defer
  url_compat: preserve-with-redirect

# ─── Risk ─────────────────────────────────────────────────────────────────────
# Every unit is scored deterministically before any model call (LOC, descriptor
# fan-out, security constraints, Spring-proxied actions, OGNL density, Unsafe).
# The score sets a tier; \`decisions.risk_ceiling\` decides what the tier means:
#   auto         nothing is held for a human
#   review-high  HIGH-tier units are staged and held until approved   (default)
#   review-all   every unit is held
risk:
  high_at: 60
  medium_at: 30

# ─── Context extraction ──────────────────────────────────────────────────────
# A pack that declares \`context:\` gets the extracted descriptor set (web.xml,
# vendor descriptors, datasources, ...) appended to its transform and review
# prompts, rendered section by section up to this many characters. Sections
# that do not fit are listed as omitted; the full context is written to
# migration-context.json in the output directory.
context:
  max_chars: 60000

# ─── LangSmith observability ─────────────────────────────────────────────────
langsmith_project: "forge-migration"
EOF

echo "==> agents.yaml written to stdout. Redirect to your target file." >&2
