"""Persist and present a discovery: the machine-readable profile, the editable
project profile, and a human summary."""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Mapping, Sequence, Tuple

from forge.discover.profile import Profile
from forge.discover.resolve import Activation

PROFILE_JSON = "stack-profile.json"
PROFILE_YAML = "forge-profile.yaml"

# Platform defaults, from prompts/FORGE-Platform-Requirements.md §4. The
# generated profile spells them out so a reader edits values, not absences.
DEFAULT_DECISIONS: Dict[str, str] = {
    "web_framework": "modernize-in-place",
    "runtime": "war-xml-bootstrap",
    "container": "liberty",
    "views": "in-place",
    "url_compat": "preserve-with-redirect",
    "persistence": "keep-orm",
    "idiom_aggressiveness": "conservative",
    "risk_ceiling": "review-high",
}


def _frameworks(profile: Profile) -> List[Tuple[str, str]]:
    """Notable framework versions, best one per family."""
    wanted = [
        ("Struts 2", "org.apache.struts", "struts2-core"), ("Struts 1", "org.apache.struts", "struts-core"),
        ("Spring", "org.springframework", "spring-core"), ("Spring Security", "org.springframework.security", "spring-security-core"),
        ("Spring Boot", "org.springframework.boot", "spring-boot"), ("Hibernate", "org.hibernate", "hibernate-core"),
        ("JUnit 4", "junit", "junit"), ("JUnit 5", "org.junit.jupiter", "junit-jupiter"), ("Mockito", "org.mockito", "mockito-core"),
        ("Servlet API (javax)", "javax.servlet", "javax.servlet-api"), ("Servlet API (jakarta)", "jakarta.servlet", "jakarta.servlet-api"),
        ("Jackson", "com.fasterxml.jackson.core", "jackson-databind"), ("JSF", "com.sun.faces", "jsf-api"),
        ("iBATIS", "org.apache.ibatis", "ibatis-sqlmap"), ("MyBatis", "org.mybatis", "mybatis"),
    ]
    out = []
    for label, group, artifact in wanted:
        deps = profile.has_dependency(group, artifact)
        if deps:
            versions = sorted({d.version or d.raw_version or "?" for d in deps})
            out.append((label, ", ".join(versions)))
    return out


def render_summary(profile: Profile, activations: Sequence[Activation], order: Sequence[str]) -> str:
    c = profile.counts
    lines = [
        f"Discovery — {profile.source_dir}",
        "",
        f"  build system   {profile.build_system}"
        + (f"  ({len(profile.modules)} module(s))" if profile.modules else ""),
        f"  java level     {profile.java_level or 'unknown'}",
        f"  sources        {c.get('.java', 0)} java ({c.get('test_java', 0)} test) · {c.get('.jsp', 0)} jsp · "
        f"{c.get('.xml', 0)} xml · {c.get('.properties', 0)} properties",
    ]
    fw = _frameworks(profile)
    if fw:
        lines.append("  frameworks     " + " · ".join(f"{k} {v}" for k, v in fw))
    if profile.descriptors:
        names = sorted({Path(d).name for d in profile.descriptors})
        lines.append(f"  descriptors    {', '.join(names[:12])}" + (" …" if len(names) > 12 else ""))
    lines.append("")

    by_id = {a.pack_id: a for a in activations}
    ordered = [by_id[p] for p in order if p in by_id]
    if not ordered:
        lines.append("  No pack's detection rules fired. Nothing to migrate, or an unsupported stack.")
        return "\n".join(lines)
    lines.append(f"  {len(ordered)} pack(s) apply, in dependency order:")
    lines.append("")
    for i, a in enumerate(ordered, 1):
        state = "runnable" if a.runnable else ("blocked" if a.complete else "detect-only")
        marker = " " if a.runnable else "*"
        lines.append(f"  {i:2}.{marker} {a.pack_id:<28} {state}")
        for e in a.evidence[:3]:
            lines.append(f"        {e}")
        if len(a.evidence) > 3:
            lines.append(f"        … {len(a.evidence) - 3} more")
    if any(not a.runnable for a in ordered):
        lines += ["", "  * detect-only packs recognise the technology but do not migrate it yet;",
                  "    blocked packs wait on a context extractor. Both are named so the gap is visible."]
    return "\n".join(lines)


def render_profile_yaml(profile: Profile, activations: Sequence[Activation], order: Sequence[str],
                        decisions: Mapping[str, str]) -> str:
    """The editable per-project profile. Comments carry the evidence."""
    by_id = {a.pack_id: a for a in activations}
    ordered = [by_id[p] for p in order if p in by_id]
    lines = [
        f"# forge-profile.yaml — generated by `migrate.py --discover` on "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d')}, then edited by you.",
        "# Remove a pack line to skip it. Decisions are the only project-specific input packs read.",
        f"source_root: {profile.source_dir}",
        f"build_system: {profile.build_system}",
        f"java_level: {profile.java_level or 'unknown'}",
        "target:",
        "  java: '21'",
        "  spring: '6.2'",
        "  jakarta: '10'",
        "",
        "packs:",
    ]
    for a in ordered:
        note = "" if a.runnable else ("   # blocked: needs a context extractor" if a.complete else "   # detect-only: recognised, not migrated")
        lines.append(f"  - {a.pack_id}{note}")
        for e in a.evidence[:2]:
            lines.append(f"      # {e}")
    lines += ["", "decisions:"]
    merged = dict(DEFAULT_DECISIONS)
    merged.update(decisions)
    for k, v in merged.items():
        lines.append(f"  {k}: {v}")
    lines += ["", "scope:", "  package_prefix: ''", "  exclude_globs: []", ""]
    return "\n".join(lines)


def write_outputs(profile: Profile, activations: Sequence[Activation], order: Sequence[str],
                  decisions: Mapping[str, str], output_dir: str) -> Tuple[Path, Path]:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    data = profile.to_json()
    data["generated_at"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
    data["activations"] = [{"pack": a.pack_id, "complete": a.complete, "runnable": a.runnable, "evidence": a.evidence}
                           for a in activations]
    data["order"] = list(order)
    json_path = out / PROFILE_JSON
    json_path.write_text(json.dumps(data, indent=2), encoding="utf-8")
    yaml_path = out / PROFILE_YAML
    yaml_path.write_text(render_profile_yaml(profile, activations, order, decisions), encoding="utf-8")
    return json_path, yaml_path
